### ISSUE TITLE
Make Video-Stack-List Component

### ISSUE THREAD

**Issue by HumbleHominid** [sciencemine/digital-signage#42]
title

**Comment by Areid406** [comment]
Initial implementation of stack-list component completed in branch "zachV". Pulls the correct video files from the DOM, hover & click events register properly, and keyboard properly cycles through videos, highlighted the current selected video via either hover or keyboard toggling.

current implementation:
content-area
           ---> stack-list
                             --->video-stack
                                                    --->video-player

Will move out of content area in future deployments.    

Currently, app will lag intermittently when cycling though videos using the keyboard. Possibly something screwy going on once a video-player component has finished playing in the context of video-stack or stack-list.
