### ISSUE TITLE
Make video-stack component

### ISSUE THREAD

**Issue by KendallSchmit** [sciencemine/digital-signage#48]
A component takes in an array of video data elements (see example model) and displays them in a "stack". It should display all the videos in the array in one at a time, in sequence for now. It should also look visually like a stack of videos (like there are more than one).

**Comment by HumbleHominid** [comment]
Use the `teaserStart` and `teaserEnd` data-members of the video pbject to specify a play time as per here: https://www.w3.org/TR/media-frags/#naming-time

**Comment by HumbleHominid** [comment]
Have `goNext` that updates url to next video in array.
Log current index.
On selected, send back current index.
Should have `isMuted` parameter changed based on passed value.

**Comment by ZachariahV** [comment]
Video-stack is closed per specifications in issue created by KendallSchmit
