### ISSUE TITLE
Create a Description Component for use by Video, Attribute List, etc. in Menu

### ISSUE THREAD

**Issue by Areid406** [sciencemine/digital-signage#63]
Generate a component that will provide descriptions for selected videos, attribute lists, etc.

**Comment by HumbleHominid** [comment]
Component will be passed a `direction` parameter for what side the popup should go on, and a  `description` parameter for the description that will should be displayed. 

Note: The component that creates any description components will have to have the timeout for rendering the component itself. Will have to add a field in the config.ui object in the model called `descriptionHoverDelay` or something. Use `setTimeout` in javascript like this: 
```js
    setTimeout(function() {
      /* do stuff */
    }, this.get('config.ui.descriptionHoverDelay') * 1000);
```

**Comment by HumbleHominid** [comment]
This is now using bootstrap popovers
