### ISSUE TITLE
Stack-List intermittently lags when cycling via keyboard

### ISSUE THREAD

**Issue by Areid406** [sciencemine/digital-signage#86]
Appears to be related to when video-player element ends.

**Comment by HumbleHominid** [comment]
I mentioned this in the meeting but it might be stemming from the video-player component. Changing `oncanplaythrough` to `oncanplay` might fix this

**Comment by HumbleHominid** [comment]
Fix is addressed in zachV branch. The parent container was getting focus from the `resetTimeout` action in `content-area.js` causing the lag
