### ISSUE TITLE
Implement After-Video-List Component 

### ISSUE THREAD

**Issue by Areid406** [sciencemine/digital-signage#90]
after-video-list is the component that will be called after playback of a video has ended, presenting related videos with varying degrees of increasing or decreasing difficulty.

Will consist of a stack-list component on top, with a video-list component on bottom.
the video-list will initially populate itself with previously viewed videos,
The stack-list component will contain related video stacks, which will populate the video-list below if a user selected a given stack.

**Comment by HumbleHominid** [comment]
Completed as per #93
