### ISSUE TITLE
Full video not playing when selected

### ISSUE THREAD

**Issue by HumbleHominid** [sciencemine/digital-signage#99]
An idle timeout is being started when a new video is selected to be played causing only the first 15s to be played before it resets back to the background.

**Comment by HumbleHominid** [comment]
`inputCallback` was being called after the `onSelectedCallback` causing the video to start playing and then having the timer reset immediately afterwords.

**Comment by Areid406** [comment]
So you’re saying the call to inputCallback was not necessary?

~Alex


On Jul 14, 2017, at 1:00 PM, Michael Fryer <notifications@github.com<mailto:notifications@github.com>> wrote:


inputCallback was being called after the onSelectedCallback causing the video to start playing and then having the timer reset immediately afterwords.

**Comment by HumbleHominid** [comment]
Fixed with https://github.com/sciencemine/digital-signage/commit/c8687a93ed52b27f97859e93aca4225babf744f3

**Comment by HumbleHominid** [comment]
It probably isn't necessary, for what we are using at least, to be calling the input callback on a select event. However, it might be in the future for some reason. To allow for future proofing I altered the order in which the callbacks are being initiated.
